services:
  minecraft-java-crossplay:
    image: itzg/minecraft-server:latest
    container_name: mc-java-server
    restart: unless-stopped
    environment:
      # Você precisa aceitar a EULA do Minecraft Java para rodar o servidor
      EULA: "TRUE"
      
      # Força o download limpo do executável do Purpur caso esteja corrompido
      FORCE_REDOWNLOAD: "true"
      
      # Alocação de memória RAM para o Java (recomenda-se deixar pelo menos 2GB livre na VPS para o SO e o Dokploy)
      MEMORY: "6G"
      
      # Desativa as flags do Aikar (desenhadas para G1GC) para usarmos o ZGC de última geração
      USE_AIKAR_FLAGS: "false"
      
      # Ativa o ZGC (automático Generational no Java 25), String Deduplication e limita o Metaspace
      JVM_XX_OPTS: "-XX:+UseZGC -XX:+UseStringDeduplication -XX:MaxMetaspaceSize=300M"
      
      # Tipo de servidor (Purpur é focado em performance extrema e 100% compatível com plugins do Paper/Spigot)
      TYPE: "PURPUR"
      VERSION: "1.21.4"
      
      # Nome do servidor e configurações de jogo
      MOTD: "§b§lNEON §d§lSYNDICATE §8| §7Crossplay Java & PE"
      DIFFICULTY: "normal"
      OPS: "" # Adicione os usernames (Java) separados por vírgula para Admin (OP) automático
      ONLINE_MODE: "true" # true = exige conta oficial para PC. Para pirata/offline, mude para false
      
      # Downloads automáticos de Plugins (GeyserMC + Floodgate + Vault + EssentialsX)
      PLUGINS: |
        https://download.geysermc.org/v2/projects/geyser/versions/latest/builds/latest/downloads/spigot
        https://download.geysermc.org/v2/projects/floodgate/versions/latest/builds/latest/downloads/spigot
        https://github.com/MilkBowl/Vault/releases/download/1.7.3/Vault.jar
        https://cdn.modrinth.com/data/hXiIvTyT/versions/SKQwLLoQ/EssentialsX-2.21.0.jar
      
      # Downloads automáticos de Plugins do Modrinth
      # Economia & Cidades: towny, luckperms, fadah
      # Construção & Mundo: fastasyncworldedit, terra, chunky
      # Gameplay & Imersão: decentholograms, traincarts, bkcommonlib, beautyquests
      MODRINTH_PROJECTS: |
        paper:towny
        luckperms
        paper:fadah
        chunky
        paper:fastasyncworldedit
        paper:terra
        paper:decentholograms
        paper:traincarts
        paper:bkcommonlib
        paper:beautyquests
      
    ports:
      # Porta padrão para computadores (Minecraft Java - TCP)
      - "25565:25565"
      # Porta padrão para celulares e consoles (Minecraft Bedrock/PE - UDP)
      - "19132:19132/udp"
      
    volumes:
      # Persistência de dados do servidor (mundos, plugins, logs)
      - ./data:/data
